# Site settings
title: Claremont Graduate University
email: tech@objectivesubject.com
description: > # this means to ignore newlines until "baseurl:"
  A pattern portfolio for Claremont Graduate University.
baseurl: "/cgu-pattern-portfolio" # the subpath of your site, e.g. /blog/
url: "http://objectivesubject.github.io/cgu-pattern-portfolio" # the base hostname & protocol for your site
twitter_username: ob_sub
github_username:  objectivesubject
github:
  repo: https://github.com/ObjectiveSubject/cgu-pattern-portfolio

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
highlighter: rouge
permalink: pretty
# sass:
#   sass_dir: ../
#   style: compressed
