# Site settings
title: CGU Pattern Portfolio
email: tech@objectivesubject.com
description: > # this means to ignore newlines until "baseurl:"
  A pattern portfolio for Claremont Graduate University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ob_sub
github_username:  objectivesubject

# Build settings
markdown: kramdown
